### PR TITLE
Added the code of conduct :sparkles:

### PR DESCRIPTION
**Pull request by heyAyushh**

### CODE REVIEW

**Review by shivankgtm — CHANGES_REQUESTED** [review]
@heyAyushh  in 'Examples of behavior that contributes to creating a positive environment include' 
the examples are coming as a paragraph instead of lines.

**Comment by heyAyushh** [comment]
@Shivank98 did those changes

**Review by shivankgtm — APPROVED** [review]

**Comment by heyAyushh** [comment]
@Shivank98 Whenever you merge choose squash and merge. I did some chaos.

**Comment by heyAyushh** [comment]
thanks @Shivank98 I am closing this request. will add more guidelines by today.

**Pull request merged**
