### PR TITLE
Add more resources

### PR DESCRIPTION
**Pull request by soumilk**
Add more text-based resources. 
Need suggestions of what else should be added to it

### CODE REVIEW

**Review by prashant0598 — COMMENTED** [review]
@soumilk Great Compilation but should we also add the installation process

**Comment by soumilk** [comment]
Yeah, sure why not guide them from the very beginning. I was actually thinking to include these points : 
1. History and how python emerged, it was there for so long but gaining popularity now. 
2. Is it better than 2 strongest languages I.e. Java and C++ ?? 
3. Who owns this language!!?
4. Why python ? 
5. Installation and initialisation
6. Introduction to some strong IDEs like pycharm, spyder. 
7. Most people go for python because of ML and data science, so is ML not possible in C++ or other languages !!? People don't know that you can do everything with C++ which it only assumed to be done through python. 
8. Why python is not much preferred in Competitive world with strict time constraints. 
Etcc.... Because these questions actually arises in people's mind.

**Comment by prashant0598** [comment]
@soumilk Should we do this as Medium Article and add links to it or make the documentation on Repo only.

**Comment by soumilk** [comment]
I have no experience with medium articles, but if you think it would be better then we can go for it. Which one would you think will have greater audience ?

**Comment by prashant0598** [comment]
@soumilk I am merging this PR. Let's forward this discussion in an issue.

**Pull request merged**
